# site settings
title: Gert Cls
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gertclaus.github.io/" # the base hostname & protocol for your site
author: Gert Claus
street_address: 1234 Somewhere Road
city: Nashville
zip_code: 55555
country: Belgium
phone: (716) 555-5555

# social settings
facebook_url: https://www.facebook.com/gert.claus
googleplus_url:
instagram_url: https://instagram.com/gertcls
linkedin_url: https://www.linkedin.com/in/gertclaus/
twitter_url: https://twitter.com/gertcls

# build settings
markdown: kramdown

sass:
  style: compressed
